library(duckdb)
duckdb_extension_storage(location="shared")
duckdb_secret_storage(location="shared")

DBI::dbExecute(con, 'INSTALL httpfs')
DBI::dbExecute(con, 'INSTALL aws')
DBI::dbExecute(con, 'INSTALL postgres')
DBI::dbExecute(con, 'INSTALL spatial')
DBI::dbExecute(con, 'INSTALL icu')
DBI::dbDisconnect(con, shutdown=TRUE)
